apiVersion: v1
kind: Service
metadata:
  name: sending-api
spec:
  selector:
    app: sending-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: 7000
    port: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sending-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sending-api
  template:
    metadata:
      labels:
        app: sending-api
    spec:
      containers:
      - name: sending-api
        image: registry.local:5000/playground/sending-api:3.1-build-6
        ports:
        - containerPort: 7000  
        env:
        - name: ASPNETCORE_URLS
          value: http://+:7000
        - name: ASPNETCORE_ENVIRONMENT
          value: Development




  

